# Generated by Django 5.0.3 on 2024-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tel_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
