# Generated by Django 5.0.3 on 2024-04-02 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inclusion_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
