# Generated by Django 5.0.3 on 2024-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_inclusion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='inclusion_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='tel_2',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tel_1',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
